[[session]]
name = "dotfiles"
path = "~/.dotfiles"
startup_script = "~/.config/sesh/scripts/dotfiles.sh"

[[session]]
name = "metqly"
path = "~/Dev/Projects/metql"
startup_script = "~/.config/sesh/scripts/dev.sh"


[[session]]
name = "qiatt"
path = "~/Dev/Projects/qiatt"
startup_script = "~/.config/sesh/scripts/dev.sh"
