---
- name: Add pacman packahes Arch-based system
  hosts: localhost
  become: yes
  tasks:

    - name: Install required packages
      ignore_errors: true
      package:
        name:
          - ripgrep
          - neovim
          
          - fish
        state: present

- name: Configure Arch-based system
  hosts: localhost
  become: no
  tasks:

    - name: Configure Git user settings
      git_config:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        scope: global
      loop:
        - { name: "user.name", value: "Daniel Brandenburg" }
        - { name: "user.email", value: "brandendj@gmail.com" }
        - { name: "core.autocrlf", value: "true" }

    - name: Create symlinks for dotfiles
      file:
        src: "{{ ansible_env.HOME }}/.dotfiles/{{ item }}"
        dest: "{{ ansible_env.HOME }}/{{ item }}"
        state: link
        force: yes
        follow: false
      loop:
        - .config/nvim
        - .config/fish
        - .config/sway
        - .config/fastfetch
        - .wezterm.lua
        - .ideavimrc
        - .profile
        - starship.toml

