unbindsym --to-code $mod+v
bindsym $mod+v exec $clipboard

bindsym $mod+F1 swayidle -w \
         timeout 3 'swaylock -f -c 000000' \
         timeout 10 'swaymsg "output * power off"' resume 'swaymsg "output * power on"' \
         before-sleep 'swaylock -f -c 000000'

